<?php $this->title = "Borrar usuario"; ?>

<div class="w-full max-w-md bg-white rounded-lg shadow-md p-6 mt-16 mx-auto">
    <div class="pt-2">
        <h2 class="text-xl font-semibold text-center mb-4">¿Seguro que deseas eliminar tu usuario?</h2>
        <form method="POST" action="<?= BASE_URL ?>/delete" class="space-y-4">
            <div class="flex justify-center space-x-4">
                <button
                    type="submit"
                    class="w-40 inline-block text-center bg-gray-300 text-gray-800 py-2 px-4 rounded-lg hover:bg-gray-400 transition">
                    SI
                </button>
                <a
                    href="<?= BASE_URL ?>/home"
                    class="w-40 bg-gray-300 text-gray-800 py-2 px-4 rounded-lg hover:bg-gray-400 transition inline-block text-center">
                    NO
                </a>
            </div>
    </div>
</div>