<?php $this->title = "Iniciar sesión"; ?>

<div class="w-full max-w-md bg-white rounded-xl shadow-md p-6 mt-16 mx-auto border border-gray-400">
    <h2 class="text-2xl font-bold mb-6 text-center">Pagina de registro</h2>

    <?php if (!empty($this->_data['error'])): ?>
        <div class="mb-4 p-4 bg-red-100 text-red-700 rounded">
            <?= htmlspecialchars($this->_data['error']) ?>
        </div>
    <?php endif; ?>

    <form action="<?= BASE_URL ?>/signup" method="POST" class="space-y-4">
        <div>
            <label class="block text-sm font-medium">Nombre</label>
            <input
                type="text"
                name="name"
                required
                class="mt-1 w-full border border-gray-300 rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500" />
        </div>

        <div>
            <label class="block text-sm font-medium">Email</label>
            <input
                type="email"
                name="email"
                required
                class="mt-1 w-full border border-gray-300 rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500" />
        </div>

        <div>
            <label class="block text-sm font-medium">Contraseña</label>
            <input
                type="password"
                name="password"
                required
                class="mt-1 w-full border border-gray-300 rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500" />
        </div>
        <div>
            <label class="block text-sm font-medium">Repetir contraseña</label>
            <input
                type="password"
                name="confirmPassword"
                required
                class="mt-1 w-full border border-gray-300 rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500" />
        </div>

        <div class="pt-2">
            <button
                type="submit"
                class="w-full bg-gray-400 text-white py-2 px-4 rounded-lg hover:bg-gray-500 transition">
                Registrarse
            </button>
        </div>
        <p class="pt-2 text-center">
            Si ya tienes una cuenta, <a href="<?= BASE_URL ?>/login" class="text-yellow-600 hover:underline">inicia sesion aqui.</a>
        </p>
    </form>
</div>