<?php $this->title = "Editar perfil"; ?>

<div class="w-full max-w-md bg-white rounded-xl shadow-md p-6 mt-16 mx-auto border border-gray-400">
    <h2 class="text-2xl font-bold mb-6 text-center">Editar perfil</h2>

    <?php if (!empty($this->_data['error'])): ?>
        <div class="mb-4 p-4 bg-red-100 text-red-700 rounded">
            <?= htmlspecialchars($this->_data['error']) ?>
        </div>
    <?php endif; ?>

    <form action="<?= BASE_URL ?>/update" method="POST" class="space-y-4">
        <div>
            <label class="block text-sm font-medium">Nombre</label>
            <input
                type="text"
                name="name"
                required
                class="mt-1 w-full border border-gray-300 rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500" />
        </div>

        <div>
            <label class="block text-sm font-medium">Email</label>
            <input
                type="email"
                name="email"
                required
                class="mt-1 w-full border border-gray-300 rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500" />
        </div>

        <div>
            <label class="block text-sm font-medium">Nueva Contraseña</label>
            <input
                type="password"
                name="newPassword"
                required
                class="mt-1 w-full border border-gray-300 rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500" />
        </div>
        <div>
            <label class="block text-sm font-medium">Confirmar contraseña</label>
            <input
                type="password"
                name="confirmPassword"
                required
                class="mt-1 w-full border border-gray-300 rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500" />
        </div>
        <p class="mt-6 text-sm">
            Si desea eliminar el usuario, 
            <a href="<?= BASE_URL ?>/deleteConfirm" class="text-yellow-600 hover:underline">pulse aqui.</a>
        </p>

        <div class="pt-2">
            <button
                type="submit"
                class="w-full inline-block text-center bg-gray-300 text-gray-800 py-2 px-4 rounded-lg hover:bg-gray-400 transition">
                Actualizar
            </button>
        </div>
        <a href="<?= BASE_URL ?>/home"
            class="w-full inline-block text-center bg-gray-300 text-gray-800 py-2 px-4 rounded-lg hover:bg-gray-400 transition">
            Volver atrás
        </a>
    </form>
</div>