<?php
$viewName = $this->title ?? '';
?>

<header class="bg-white shadow-md w-full">
	<div class="max-w-7xl mx-auto px-4 py-4 flex justify-between items-center">
		<div class="flex items-center gap-2">
			<img src="\images\logo-taskify.svg" alt="Logo" class="w-10 h-10" />
		</div>
		<div class="space-x-4 text-sm">
			<?php if ($viewName === 'MiGestor' || $viewName === 'Registro' || $viewName === 'Iniciar sesión') : ?>
				<a href="<?= BASE_URL ?>/login" class="text-yellow-600 hover:underline">Iniciar sesión</a>
			<?php elseif ($viewName === 'Cerrar sesión') : ?>
				<a href="<?= BASE_URL ?>/login" class="text-yellow-600 hover:underline">Iniciar sesión</a>
				<a href="<?= BASE_URL ?>/" class="text-yellow-600 hover:underline">Inicio</a>
			<?php else : ?>
				<a href="<?= BASE_URL ?>/logout" class="text-yellow-600 hover:underline">Cerrar sesión</a>
			<?php endif; ?>
		</div>
	</div>
</header>
